[theme]
primaryColor="#4F111A"
backgroundColor="#0D0F40"
secondaryBackgroundColor="#FFFFF"
textColor="#2E2E2E"
font = "Yuyu"
codeFont = "Yuyu:https://fonts.googleapis.com/css2?family=Yuyu&display=swap" 
