[theme]
primaryColor="#6B4F4F"
backgroundColor="#FAF8F4"
secondaryBackgroundColor="#E8E3D9"
textColor="#2E2E2E"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
